name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend-static-webapp.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: cert-practice-question-env
    name: Build and Deploy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Create .env file for production
        working-directory: ./frontend
        run: |
          # Use the backend Web App URL
          BACKEND_URL="https://backend-ai-practice-questions-app.azurewebsites.net"
          API_URL="${BACKEND_URL}/api/v1"
          
          echo "REACT_APP_API_URL=${API_URL}" > .env
          echo "REACT_APP_ENV=production" >> .env
          
          echo "Frontend will connect to: ${API_URL}"

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        env:
          CI: false
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Deploy to Azure Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/build"
          output_location: ""
          skip_app_build: true

      - name: Deployment Summary
        run: |
          echo "## 🎉 Frontend Deployment to Azure Static Web App" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Status: ✅ Deployed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Backend API" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: https://backend-ai-practice-questions-app.azurewebsites.net/api/v1" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Note the Static Web App URL from the deployment output above" >> $GITHUB_STEP_SUMMARY
          echo "2. Update backend CORS to include the Static Web App URL" >> $GITHUB_STEP_SUMMARY
          echo "3. Test the frontend at the Static Web App URL" >> $GITHUB_STEP_SUMMARY
